// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package store

import (
	"context"
	"database/sql"
)

const bestLinkageTargetCandidates = `-- name: BestLinkageTargetCandidates :many
SELECT
    v.linkage_target_id,
    v.description,
    v.begin_year_month,
    v.end_year_month,
    v.fuel_type,
    v.capacity_cc,
    v.horse_power_from,
    COUNT(*)::int AS part_count
FROM vehicle_lookup v
JOIN hk_parts_cache hk ON hk.linking_target_id = v.linkage_target_id
WHERE v.nhtsa_make = $1
  AND v.nhtsa_model = $2
  AND $3 BETWEEN v.year_from AND v.year_to
GROUP BY
    v.linkage_target_id,
    v.description,
    v.begin_year_month,
    v.end_year_month,
    v.fuel_type,
    v.capacity_cc,
    v.horse_power_from
ORDER BY part_count DESC, v.begin_year_month DESC
LIMIT 20
`

type BestLinkageTargetCandidatesParams struct {
	NhtsaMake  string
	NhtsaModel string
	YearFrom   int32
}

type BestLinkageTargetCandidatesRow struct {
	LinkageTargetID int32
	Description     string
	BeginYearMonth  sql.NullString
	EndYearMonth    sql.NullString
	FuelType        sql.NullString
	CapacityCc      sql.NullInt32
	HorsePowerFrom  sql.NullInt32
	PartCount       int32
}

func (q *Queries) BestLinkageTargetCandidates(ctx context.Context, arg BestLinkageTargetCandidatesParams) ([]BestLinkageTargetCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, bestLinkageTargetCandidates, arg.NhtsaMake, arg.NhtsaModel, arg.YearFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BestLinkageTargetCandidatesRow{}
	for rows.Next() {
		var i BestLinkageTargetCandidatesRow
		if err := rows.Scan(
			&i.LinkageTargetID,
			&i.Description,
			&i.BeginYearMonth,
			&i.EndYearMonth,
			&i.FuelType,
			&i.CapacityCc,
			&i.HorsePowerFrom,
			&i.PartCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const categoryTreeLeavesByVehicle = `-- name: CategoryTreeLeavesByVehicle :many
SELECT
    COALESCE(category_name, '') AS category_name,
    assembly_group_node_id,
    COUNT(DISTINCT legacy_article_id)::int AS part_count
FROM hk_parts_cache
WHERE linking_target_id = $1
  AND category_name IS NOT NULL
  AND category_name != ''
GROUP BY category_name, assembly_group_node_id
ORDER BY category_name
`

type CategoryTreeLeavesByVehicleRow struct {
	CategoryName        string
	AssemblyGroupNodeID int32
	PartCount           int32
}

func (q *Queries) CategoryTreeLeavesByVehicle(ctx context.Context, linkingTargetID int32) ([]CategoryTreeLeavesByVehicleRow, error) {
	rows, err := q.db.QueryContext(ctx, categoryTreeLeavesByVehicle, linkingTargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryTreeLeavesByVehicleRow{}
	for rows.Next() {
		var i CategoryTreeLeavesByVehicleRow
		if err := rows.Scan(&i.CategoryName, &i.AssemblyGroupNodeID, &i.PartCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkPartFitsVehicle = `-- name: CheckPartFitsVehicle :one
SELECT EXISTS (
    SELECT 1
    FROM hk_parts_cache
    WHERE linking_target_id = $1
      AND legacy_article_id = $2
)
`

type CheckPartFitsVehicleParams struct {
	LinkingTargetID int32
	LegacyArticleID int32
}

func (q *Queries) CheckPartFitsVehicle(ctx context.Context, arg CheckPartFitsVehicleParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkPartFitsVehicle, arg.LinkingTargetID, arg.LegacyArticleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countPartsByVehicleCategory = `-- name: CountPartsByVehicleCategory :one
SELECT COUNT(DISTINCT legacy_article_id)::int
FROM hk_parts_cache
WHERE linking_target_id = $1
  AND ($2::text = '' OR COALESCE(category_name, '') ILIKE '%' || $2 || '%')
`

type CountPartsByVehicleCategoryParams struct {
	LinkingTargetID int32
	Column2         string
}

func (q *Queries) CountPartsByVehicleCategory(ctx context.Context, arg CountPartsByVehicleCategoryParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countPartsByVehicleCategory, arg.LinkingTargetID, arg.Column2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSourcesByRecommendation = `-- name: CountSourcesByRecommendation :many
SELECT recommendation, COUNT(*)::int AS source_count
FROM external_sources
GROUP BY recommendation
`

type CountSourcesByRecommendationRow struct {
	Recommendation string
	SourceCount    int32
}

func (q *Queries) CountSourcesByRecommendation(ctx context.Context) ([]CountSourcesByRecommendationRow, error) {
	rows, err := q.db.QueryContext(ctx, countSourcesByRecommendation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSourcesByRecommendationRow{}
	for rows.Next() {
		var i CountSourcesByRecommendationRow
		if err := rows.Scan(&i.Recommendation, &i.SourceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countVehicleSearchParts = `-- name: CountVehicleSearchParts :one
SELECT COUNT(DISTINCT legacy_article_id)::int
FROM hk_parts_cache
WHERE linking_target_id = $1
  AND ($2::text = '' OR (COALESCE(generic_article_desc, '') ILIKE '%' || $2 || '%' OR COALESCE(category_name, '') ILIKE '%' || $2 || '%'))
  AND (
    $3::text = ''
    OR (
      NOT EXISTS (
        SELECT 1
        FROM unnest(regexp_split_to_array($3, '\s+')) AS query_token(token)
        WHERE concat_ws(' ', generic_article_desc, article_number, category_name) NOT ILIKE '%' || query_token.token || '%'
      )
      AND EXISTS (
        SELECT 1
        FROM unnest(regexp_split_to_array($3, '\s+')) AS query_token(token)
        WHERE concat_ws(' ', generic_article_desc, article_number) ILIKE '%' || query_token.token || '%'
      )
    )
  )
`

type CountVehicleSearchPartsParams struct {
	LinkingTargetID int32
	Column2         string
	Column3         string
}

func (q *Queries) CountVehicleSearchParts(ctx context.Context, arg CountVehicleSearchPartsParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countVehicleSearchParts, arg.LinkingTargetID, arg.Column2, arg.Column3)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const findAlternativesForArticleAnyVehicle = `-- name: FindAlternativesForArticleAnyVehicle :many
SELECT DISTINCT ON (legacy_article_id)
    legacy_article_id,
    article_number,
    generic_article_desc,
    brand_name,
    category_name,
    assembly_group_node_id
FROM hk_parts_cache
WHERE generic_article_desc = $1
  AND legacy_article_id != $2
ORDER BY legacy_article_id, brand_name
LIMIT $3
`

type FindAlternativesForArticleAnyVehicleParams struct {
	GenericArticleDesc sql.NullString
	LegacyArticleID    int32
	Limit              int32
}

type FindAlternativesForArticleAnyVehicleRow struct {
	LegacyArticleID     int32
	ArticleNumber       sql.NullString
	GenericArticleDesc  sql.NullString
	BrandName           sql.NullString
	CategoryName        sql.NullString
	AssemblyGroupNodeID int32
}

func (q *Queries) FindAlternativesForArticleAnyVehicle(ctx context.Context, arg FindAlternativesForArticleAnyVehicleParams) ([]FindAlternativesForArticleAnyVehicleRow, error) {
	rows, err := q.db.QueryContext(ctx, findAlternativesForArticleAnyVehicle, arg.GenericArticleDesc, arg.LegacyArticleID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAlternativesForArticleAnyVehicleRow{}
	for rows.Next() {
		var i FindAlternativesForArticleAnyVehicleRow
		if err := rows.Scan(
			&i.LegacyArticleID,
			&i.ArticleNumber,
			&i.GenericArticleDesc,
			&i.BrandName,
			&i.CategoryName,
			&i.AssemblyGroupNodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAlternativesForArticleVehicle = `-- name: FindAlternativesForArticleVehicle :many
SELECT DISTINCT ON (legacy_article_id)
    legacy_article_id,
    article_number,
    generic_article_desc,
    brand_name,
    category_name,
    assembly_group_node_id
FROM hk_parts_cache
WHERE generic_article_desc = $1
  AND linking_target_id = $2
  AND legacy_article_id != $3
ORDER BY legacy_article_id, brand_name
LIMIT $4
`

type FindAlternativesForArticleVehicleParams struct {
	GenericArticleDesc sql.NullString
	LinkingTargetID    int32
	LegacyArticleID    int32
	Limit              int32
}

type FindAlternativesForArticleVehicleRow struct {
	LegacyArticleID     int32
	ArticleNumber       sql.NullString
	GenericArticleDesc  sql.NullString
	BrandName           sql.NullString
	CategoryName        sql.NullString
	AssemblyGroupNodeID int32
}

func (q *Queries) FindAlternativesForArticleVehicle(ctx context.Context, arg FindAlternativesForArticleVehicleParams) ([]FindAlternativesForArticleVehicleRow, error) {
	rows, err := q.db.QueryContext(ctx, findAlternativesForArticleVehicle,
		arg.GenericArticleDesc,
		arg.LinkingTargetID,
		arg.LegacyArticleID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAlternativesForArticleVehicleRow{}
	for rows.Next() {
		var i FindAlternativesForArticleVehicleRow
		if err := rows.Scan(
			&i.LegacyArticleID,
			&i.ArticleNumber,
			&i.GenericArticleDesc,
			&i.BrandName,
			&i.CategoryName,
			&i.AssemblyGroupNodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOEMReferencesForArticle = `-- name: FindOEMReferencesForArticle :many
SELECT
    raw_number,
    mfr_name,
    article_number,
    description
FROM oem_search_index
WHERE legacy_article_id = $1
LIMIT 50
`

type FindOEMReferencesForArticleRow struct {
	RawNumber     string
	MfrName       sql.NullString
	ArticleNumber sql.NullString
	Description   sql.NullString
}

func (q *Queries) FindOEMReferencesForArticle(ctx context.Context, legacyArticleID int32) ([]FindOEMReferencesForArticleRow, error) {
	rows, err := q.db.QueryContext(ctx, findOEMReferencesForArticle, legacyArticleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindOEMReferencesForArticleRow{}
	for rows.Next() {
		var i FindOEMReferencesForArticleRow
		if err := rows.Scan(
			&i.RawNumber,
			&i.MfrName,
			&i.ArticleNumber,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPartByArticleAnyVehicle = `-- name: FindPartByArticleAnyVehicle :one
SELECT legacy_article_id, article_number, generic_article_desc, brand_name, category_name, assembly_group_node_id
FROM hk_parts_cache
WHERE legacy_article_id = $1
LIMIT 1
`

type FindPartByArticleAnyVehicleRow struct {
	LegacyArticleID     int32
	ArticleNumber       sql.NullString
	GenericArticleDesc  sql.NullString
	BrandName           sql.NullString
	CategoryName        sql.NullString
	AssemblyGroupNodeID int32
}

func (q *Queries) FindPartByArticleAnyVehicle(ctx context.Context, legacyArticleID int32) (FindPartByArticleAnyVehicleRow, error) {
	row := q.db.QueryRowContext(ctx, findPartByArticleAnyVehicle, legacyArticleID)
	var i FindPartByArticleAnyVehicleRow
	err := row.Scan(
		&i.LegacyArticleID,
		&i.ArticleNumber,
		&i.GenericArticleDesc,
		&i.BrandName,
		&i.CategoryName,
		&i.AssemblyGroupNodeID,
	)
	return i, err
}

const findPartByArticleForVehicle = `-- name: FindPartByArticleForVehicle :one
SELECT legacy_article_id, article_number, generic_article_desc, brand_name, category_name, assembly_group_node_id
FROM hk_parts_cache
WHERE legacy_article_id = $1
  AND linking_target_id = $2
LIMIT 1
`

type FindPartByArticleForVehicleParams struct {
	LegacyArticleID int32
	LinkingTargetID int32
}

type FindPartByArticleForVehicleRow struct {
	LegacyArticleID     int32
	ArticleNumber       sql.NullString
	GenericArticleDesc  sql.NullString
	BrandName           sql.NullString
	CategoryName        sql.NullString
	AssemblyGroupNodeID int32
}

func (q *Queries) FindPartByArticleForVehicle(ctx context.Context, arg FindPartByArticleForVehicleParams) (FindPartByArticleForVehicleRow, error) {
	row := q.db.QueryRowContext(ctx, findPartByArticleForVehicle, arg.LegacyArticleID, arg.LinkingTargetID)
	var i FindPartByArticleForVehicleRow
	err := row.Scan(
		&i.LegacyArticleID,
		&i.ArticleNumber,
		&i.GenericArticleDesc,
		&i.BrandName,
		&i.CategoryName,
		&i.AssemblyGroupNodeID,
	)
	return i, err
}

const findPlatformSiblingsForHyundai = `-- name: FindPlatformSiblingsForHyundai :many
SELECT 'KIA' AS sibling_make, kia_model AS sibling_model, platform_code
FROM hk_platform_map
WHERE UPPER(hyundai_model) = UPPER($1)
`

type FindPlatformSiblingsForHyundaiRow struct {
	SiblingMake  string
	SiblingModel string
	PlatformCode string
}

func (q *Queries) FindPlatformSiblingsForHyundai(ctx context.Context, upper interface{}) ([]FindPlatformSiblingsForHyundaiRow, error) {
	rows, err := q.db.QueryContext(ctx, findPlatformSiblingsForHyundai, upper)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlatformSiblingsForHyundaiRow{}
	for rows.Next() {
		var i FindPlatformSiblingsForHyundaiRow
		if err := rows.Scan(&i.SiblingMake, &i.SiblingModel, &i.PlatformCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlatformSiblingsForKia = `-- name: FindPlatformSiblingsForKia :many
SELECT 'HYUNDAI' AS sibling_make, hyundai_model AS sibling_model, platform_code
FROM hk_platform_map
WHERE UPPER(kia_model) = UPPER($1)
`

type FindPlatformSiblingsForKiaRow struct {
	SiblingMake  string
	SiblingModel string
	PlatformCode string
}

func (q *Queries) FindPlatformSiblingsForKia(ctx context.Context, upper interface{}) ([]FindPlatformSiblingsForKiaRow, error) {
	rows, err := q.db.QueryContext(ctx, findPlatformSiblingsForKia, upper)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlatformSiblingsForKiaRow{}
	for rows.Next() {
		var i FindPlatformSiblingsForKiaRow
		if err := rows.Scan(&i.SiblingMake, &i.SiblingModel, &i.PlatformCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findVehiclesForArticle = `-- name: FindVehiclesForArticle :many
SELECT DISTINCT
    linking_target_id,
    vehicle_desc,
    begin_year_month,
    end_year_month,
    fuel_type,
    capacity_cc,
    horse_power_from,
    CASE manu_id WHEN 183 THEN 'HYUNDAI' WHEN 184 THEN 'KIA' ELSE '' END AS make_name
FROM hk_parts_cache
WHERE legacy_article_id = $1
ORDER BY make_name, vehicle_desc
LIMIT $2
`

type FindVehiclesForArticleParams struct {
	LegacyArticleID int32
	Limit           int32
}

type FindVehiclesForArticleRow struct {
	LinkingTargetID int32
	VehicleDesc     sql.NullString
	BeginYearMonth  sql.NullString
	EndYearMonth    sql.NullString
	FuelType        sql.NullString
	CapacityCc      sql.NullInt32
	HorsePowerFrom  sql.NullInt32
	MakeName        string
}

func (q *Queries) FindVehiclesForArticle(ctx context.Context, arg FindVehiclesForArticleParams) ([]FindVehiclesForArticleRow, error) {
	rows, err := q.db.QueryContext(ctx, findVehiclesForArticle, arg.LegacyArticleID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindVehiclesForArticleRow{}
	for rows.Next() {
		var i FindVehiclesForArticleRow
		if err := rows.Scan(
			&i.LinkingTargetID,
			&i.VehicleDesc,
			&i.BeginYearMonth,
			&i.EndYearMonth,
			&i.FuelType,
			&i.CapacityCc,
			&i.HorsePowerFrom,
			&i.MakeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssemblyGroupsByVehicle = `-- name: ListAssemblyGroupsByVehicle :many
SELECT
    assembly_group_node_id,
    COALESCE(category_name, '') AS category_name,
    COUNT(DISTINCT legacy_article_id)::int AS part_count
FROM hk_parts_cache
WHERE linking_target_id = $1
  AND assembly_group_node_id > 0
GROUP BY assembly_group_node_id, category_name
ORDER BY category_name
`

type ListAssemblyGroupsByVehicleRow struct {
	AssemblyGroupNodeID int32
	CategoryName        string
	PartCount           int32
}

func (q *Queries) ListAssemblyGroupsByVehicle(ctx context.Context, linkingTargetID int32) ([]ListAssemblyGroupsByVehicleRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssemblyGroupsByVehicle, linkingTargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssemblyGroupsByVehicleRow{}
	for rows.Next() {
		var i ListAssemblyGroupsByVehicleRow
		if err := rows.Scan(&i.AssemblyGroupNodeID, &i.CategoryName, &i.PartCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryInfos = `-- name: ListCategoryInfos :many
SELECT
    generic_article_desc,
    COUNT(DISTINCT legacy_article_id)::int AS part_count
FROM hk_parts_cache
WHERE linking_target_id = $1
  AND generic_article_desc IS NOT NULL
  AND generic_article_desc != ''
GROUP BY generic_article_desc
ORDER BY part_count DESC
`

type ListCategoryInfosRow struct {
	GenericArticleDesc sql.NullString
	PartCount          int32
}

func (q *Queries) ListCategoryInfos(ctx context.Context, linkingTargetID int32) ([]ListCategoryInfosRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategoryInfos, linkingTargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoryInfosRow{}
	for rows.Next() {
		var i ListCategoryInfosRow
		if err := rows.Scan(&i.GenericArticleDesc, &i.PartCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsByMake = `-- name: ListModelsByMake :many
SELECT
    nhtsa_model,
    MIN(year_from)::int AS year_from,
    MAX(year_to)::int AS year_to,
    COUNT(DISTINCT linkage_target_id)::int AS variants
FROM vehicle_lookup
WHERE nhtsa_make = $1
GROUP BY nhtsa_model
ORDER BY nhtsa_model
`

type ListModelsByMakeRow struct {
	NhtsaModel string
	YearFrom   int32
	YearTo     int32
	Variants   int32
}

func (q *Queries) ListModelsByMake(ctx context.Context, nhtsaMake string) ([]ListModelsByMakeRow, error) {
	rows, err := q.db.QueryContext(ctx, listModelsByMake, nhtsaMake)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelsByMakeRow{}
	for rows.Next() {
		var i ListModelsByMakeRow
		if err := rows.Scan(
			&i.NhtsaModel,
			&i.YearFrom,
			&i.YearTo,
			&i.Variants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOEMRawNumbersForArticle = `-- name: ListOEMRawNumbersForArticle :many
SELECT DISTINCT raw_number
FROM oem_search_index
WHERE legacy_article_id = $1
LIMIT 20
`

func (q *Queries) ListOEMRawNumbersForArticle(ctx context.Context, legacyArticleID int32) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listOEMRawNumbersForArticle, legacyArticleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var raw_number string
		if err := rows.Scan(&raw_number); err != nil {
			return nil, err
		}
		items = append(items, raw_number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartsByGroup = `-- name: ListPartsByGroup :many
SELECT DISTINCT ON (legacy_article_id)
    legacy_article_id,
    article_number,
    generic_article_desc,
    brand_name,
    category_name,
    assembly_group_node_id
FROM hk_parts_cache
WHERE linking_target_id = $1
  AND ($2::int = 0 OR assembly_group_node_id = $2)
ORDER BY legacy_article_id, category_name, generic_article_desc, brand_name
`

type ListPartsByGroupParams struct {
	LinkingTargetID int32
	Column2         int32
}

type ListPartsByGroupRow struct {
	LegacyArticleID     int32
	ArticleNumber       sql.NullString
	GenericArticleDesc  sql.NullString
	BrandName           sql.NullString
	CategoryName        sql.NullString
	AssemblyGroupNodeID int32
}

func (q *Queries) ListPartsByGroup(ctx context.Context, arg ListPartsByGroupParams) ([]ListPartsByGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, listPartsByGroup, arg.LinkingTargetID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPartsByGroupRow{}
	for rows.Next() {
		var i ListPartsByGroupRow
		if err := rows.Scan(
			&i.LegacyArticleID,
			&i.ArticleNumber,
			&i.GenericArticleDesc,
			&i.BrandName,
			&i.CategoryName,
			&i.AssemblyGroupNodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartsByVehicleCategory = `-- name: ListPartsByVehicleCategory :many
SELECT DISTINCT ON (legacy_article_id)
    legacy_article_id,
    article_number,
    generic_article_desc,
    brand_name,
    category_name,
    assembly_group_node_id
FROM hk_parts_cache
WHERE linking_target_id = $1
  AND ($2::text = '' OR COALESCE(category_name, '') ILIKE '%' || $2 || '%')
ORDER BY legacy_article_id, category_name, brand_name
LIMIT $3 OFFSET $4
`

type ListPartsByVehicleCategoryParams struct {
	LinkingTargetID int32
	Column2         string
	Limit           int32
	Offset          int32
}

type ListPartsByVehicleCategoryRow struct {
	LegacyArticleID     int32
	ArticleNumber       sql.NullString
	GenericArticleDesc  sql.NullString
	BrandName           sql.NullString
	CategoryName        sql.NullString
	AssemblyGroupNodeID int32
}

func (q *Queries) ListPartsByVehicleCategory(ctx context.Context, arg ListPartsByVehicleCategoryParams) ([]ListPartsByVehicleCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listPartsByVehicleCategory,
		arg.LinkingTargetID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPartsByVehicleCategoryRow{}
	for rows.Next() {
		var i ListPartsByVehicleCategoryRow
		if err := rows.Scan(
			&i.LegacyArticleID,
			&i.ArticleNumber,
			&i.GenericArticleDesc,
			&i.BrandName,
			&i.CategoryName,
			&i.AssemblyGroupNodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubstitutionLinksForArticle = `-- name: ListSubstitutionLinksForArticle :many
WITH article_numbers AS (
    SELECT DISTINCT UPPER(article_number) AS article_number
    FROM hk_parts_cache
    WHERE legacy_article_id = $1
      AND article_number IS NOT NULL
      AND article_number != ''
),
raw_links AS (
    SELECT
        links.to_part_number AS article_number,
        links.description,
        'reported_replacement' AS direction,
        links.source_key,
        links.source_label,
        links.source_detail,
        links.source_warning,
        links.confidence
    FROM substitution_links links
    JOIN article_numbers current_part
      ON UPPER(links.from_part_number) = current_part.article_number
    UNION ALL
    SELECT
        links.from_part_number AS article_number,
        links.description,
        'reported_predecessor' AS direction,
        links.source_key,
        links.source_label,
        links.source_detail,
        links.source_warning,
        links.confidence
    FROM substitution_links links
    JOIN article_numbers current_part
      ON UPPER(links.to_part_number) = current_part.article_number
)
SELECT
    article_number,
    COALESCE(MIN(description), '')::text AS description,
    (
      CASE
        WHEN COUNT(DISTINCT direction) > 1 THEN 'reported_related'
        ELSE MIN(direction)
      END
    )::text AS direction,
    source_key,
    COALESCE(MIN(source_label), '')::text AS source_label,
    COALESCE(MIN(source_detail), '')::text AS source_detail,
    COALESCE(MIN(source_warning), '')::text AS source_warning,
    MIN(confidence)::double precision AS confidence
FROM raw_links
GROUP BY article_number, source_key
ORDER BY article_number
LIMIT 20
`

type ListSubstitutionLinksForArticleRow struct {
	ArticleNumber string
	Description   string
	Direction     string
	SourceKey     string
	SourceLabel   string
	SourceDetail  string
	SourceWarning string
	Confidence    float64
}

func (q *Queries) ListSubstitutionLinksForArticle(ctx context.Context, legacyArticleID int32) ([]ListSubstitutionLinksForArticleRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubstitutionLinksForArticle, legacyArticleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubstitutionLinksForArticleRow{}
	for rows.Next() {
		var i ListSubstitutionLinksForArticleRow
		if err := rows.Scan(
			&i.ArticleNumber,
			&i.Description,
			&i.Direction,
			&i.SourceKey,
			&i.SourceLabel,
			&i.SourceDetail,
			&i.SourceWarning,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleSearchCategories = `-- name: ListVehicleSearchCategories :many
SELECT DISTINCT generic_article_desc
FROM hk_parts_cache
WHERE linking_target_id = $1
  AND generic_article_desc IS NOT NULL
  AND generic_article_desc != ''
ORDER BY generic_article_desc
`

func (q *Queries) ListVehicleSearchCategories(ctx context.Context, linkingTargetID int32) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listVehicleSearchCategories, linkingTargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var generic_article_desc sql.NullString
		if err := rows.Scan(&generic_article_desc); err != nil {
			return nil, err
		}
		items = append(items, generic_article_desc)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleSearchParts = `-- name: ListVehicleSearchParts :many
SELECT DISTINCT ON (legacy_article_id)
    legacy_article_id,
    article_number,
    generic_article_desc,
    brand_name,
    category_name,
    assembly_group_node_id,
    capacity_cc,
    fuel_type
FROM hk_parts_cache
WHERE linking_target_id = $1
  AND ($2::text = '' OR (COALESCE(generic_article_desc, '') ILIKE '%' || $2 || '%' OR COALESCE(category_name, '') ILIKE '%' || $2 || '%'))
  AND (
    $3::text = ''
    OR (
      NOT EXISTS (
        SELECT 1
        FROM unnest(regexp_split_to_array($3, '\s+')) AS query_token(token)
        WHERE concat_ws(' ', generic_article_desc, article_number, category_name) NOT ILIKE '%' || query_token.token || '%'
      )
      AND EXISTS (
        SELECT 1
        FROM unnest(regexp_split_to_array($3, '\s+')) AS query_token(token)
        WHERE concat_ws(' ', generic_article_desc, article_number) ILIKE '%' || query_token.token || '%'
      )
    )
  )
ORDER BY legacy_article_id, generic_article_desc, brand_name
LIMIT $4 OFFSET $5
`

type ListVehicleSearchPartsParams struct {
	LinkingTargetID int32
	Column2         string
	Column3         string
	Limit           int32
	Offset          int32
}

type ListVehicleSearchPartsRow struct {
	LegacyArticleID     int32
	ArticleNumber       sql.NullString
	GenericArticleDesc  sql.NullString
	BrandName           sql.NullString
	CategoryName        sql.NullString
	AssemblyGroupNodeID int32
	CapacityCc          sql.NullInt32
	FuelType            sql.NullString
}

func (q *Queries) ListVehicleSearchParts(ctx context.Context, arg ListVehicleSearchPartsParams) ([]ListVehicleSearchPartsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVehicleSearchParts,
		arg.LinkingTargetID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVehicleSearchPartsRow{}
	for rows.Next() {
		var i ListVehicleSearchPartsRow
		if err := rows.Scan(
			&i.LegacyArticleID,
			&i.ArticleNumber,
			&i.GenericArticleDesc,
			&i.BrandName,
			&i.CategoryName,
			&i.AssemblyGroupNodeID,
			&i.CapacityCc,
			&i.FuelType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleVariantsByMakeModel = `-- name: ListVehicleVariantsByMakeModel :many
SELECT
    linkage_target_id,
    description,
    COALESCE(fuel_type, '') AS fuel_type,
    COALESCE(capacity_cc, 0)::int AS capacity_cc,
    COALESCE(horse_power_from, 0)::int AS horse_power_from,
    year_from,
    year_to
FROM vehicle_lookup
WHERE nhtsa_make = $1
  AND nhtsa_model = $2
ORDER BY year_from DESC, capacity_cc, linkage_target_id
`

type ListVehicleVariantsByMakeModelParams struct {
	NhtsaMake  string
	NhtsaModel string
}

type ListVehicleVariantsByMakeModelRow struct {
	LinkageTargetID int32
	Description     string
	FuelType        string
	CapacityCc      int32
	HorsePowerFrom  int32
	YearFrom        int32
	YearTo          int32
}

func (q *Queries) ListVehicleVariantsByMakeModel(ctx context.Context, arg ListVehicleVariantsByMakeModelParams) ([]ListVehicleVariantsByMakeModelRow, error) {
	rows, err := q.db.QueryContext(ctx, listVehicleVariantsByMakeModel, arg.NhtsaMake, arg.NhtsaModel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVehicleVariantsByMakeModelRow{}
	for rows.Next() {
		var i ListVehicleVariantsByMakeModelRow
		if err := rows.Scan(
			&i.LinkageTargetID,
			&i.Description,
			&i.FuelType,
			&i.CapacityCc,
			&i.HorsePowerFrom,
			&i.YearFrom,
			&i.YearTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupAlternativeDescription = `-- name: LookupAlternativeDescription :one
SELECT generic_article_desc
FROM hk_parts_cache
WHERE legacy_article_id = $1
LIMIT 1
`

func (q *Queries) LookupAlternativeDescription(ctx context.Context, legacyArticleID int32) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, lookupAlternativeDescription, legacyArticleID)
	var generic_article_desc sql.NullString
	err := row.Scan(&generic_article_desc)
	return generic_article_desc, err
}

const resolveLinkageTargets = `-- name: ResolveLinkageTargets :many
SELECT DISTINCT
    linkage_target_id,
    description,
    begin_year_month,
    end_year_month,
    fuel_type,
    capacity_cc,
    horse_power_from
FROM vehicle_lookup
WHERE nhtsa_make = $1
  AND nhtsa_model = $2
  AND $3 BETWEEN year_from AND year_to
ORDER BY begin_year_month DESC, linkage_target_id
`

type ResolveLinkageTargetsParams struct {
	NhtsaMake  string
	NhtsaModel string
	YearFrom   int32
}

type ResolveLinkageTargetsRow struct {
	LinkageTargetID int32
	Description     string
	BeginYearMonth  sql.NullString
	EndYearMonth    sql.NullString
	FuelType        sql.NullString
	CapacityCc      sql.NullInt32
	HorsePowerFrom  sql.NullInt32
}

func (q *Queries) ResolveLinkageTargets(ctx context.Context, arg ResolveLinkageTargetsParams) ([]ResolveLinkageTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, resolveLinkageTargets, arg.NhtsaMake, arg.NhtsaModel, arg.YearFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveLinkageTargetsRow{}
	for rows.Next() {
		var i ResolveLinkageTargetsRow
		if err := rows.Scan(
			&i.LinkageTargetID,
			&i.Description,
			&i.BeginYearMonth,
			&i.EndYearMonth,
			&i.FuelType,
			&i.CapacityCc,
			&i.HorsePowerFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reverseVehiclesByArticle = `-- name: ReverseVehiclesByArticle :many
SELECT DISTINCT
    linking_target_id,
    vehicle_desc,
    begin_year_month,
    end_year_month,
    fuel_type,
    capacity_cc,
    horse_power_from,
    model_name,
    CASE manu_id WHEN 183 THEN 'HYUNDAI' WHEN 184 THEN 'KIA' ELSE '' END AS make_name
FROM hk_parts_cache
WHERE legacy_article_id = $1
ORDER BY make_name, model_name
LIMIT $2
`

type ReverseVehiclesByArticleParams struct {
	LegacyArticleID int32
	Limit           int32
}

type ReverseVehiclesByArticleRow struct {
	LinkingTargetID int32
	VehicleDesc     sql.NullString
	BeginYearMonth  sql.NullString
	EndYearMonth    sql.NullString
	FuelType        sql.NullString
	CapacityCc      sql.NullInt32
	HorsePowerFrom  sql.NullInt32
	ModelName       sql.NullString
	MakeName        string
}

func (q *Queries) ReverseVehiclesByArticle(ctx context.Context, arg ReverseVehiclesByArticleParams) ([]ReverseVehiclesByArticleRow, error) {
	rows, err := q.db.QueryContext(ctx, reverseVehiclesByArticle, arg.LegacyArticleID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReverseVehiclesByArticleRow{}
	for rows.Next() {
		var i ReverseVehiclesByArticleRow
		if err := rows.Scan(
			&i.LinkingTargetID,
			&i.VehicleDesc,
			&i.BeginYearMonth,
			&i.EndYearMonth,
			&i.FuelType,
			&i.CapacityCc,
			&i.HorsePowerFrom,
			&i.ModelName,
			&i.MakeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByArticleNumber = `-- name: SearchByArticleNumber :many
SELECT DISTINCT ON (legacy_article_id)
    legacy_article_id,
    article_number,
    generic_article_desc,
    brand_name,
    category_name,
    assembly_group_node_id,
    capacity_cc
FROM hk_parts_cache
WHERE UPPER(article_number) = UPPER($1)
ORDER BY legacy_article_id
LIMIT $2
`

type SearchByArticleNumberParams struct {
	Upper interface{}
	Limit int32
}

type SearchByArticleNumberRow struct {
	LegacyArticleID     int32
	ArticleNumber       sql.NullString
	GenericArticleDesc  sql.NullString
	BrandName           sql.NullString
	CategoryName        sql.NullString
	AssemblyGroupNodeID int32
	CapacityCc          sql.NullInt32
}

func (q *Queries) SearchByArticleNumber(ctx context.Context, arg SearchByArticleNumberParams) ([]SearchByArticleNumberRow, error) {
	rows, err := q.db.QueryContext(ctx, searchByArticleNumber, arg.Upper, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchByArticleNumberRow{}
	for rows.Next() {
		var i SearchByArticleNumberRow
		if err := rows.Scan(
			&i.LegacyArticleID,
			&i.ArticleNumber,
			&i.GenericArticleDesc,
			&i.BrandName,
			&i.CategoryName,
			&i.AssemblyGroupNodeID,
			&i.CapacityCc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByText = `-- name: SearchByText :many
SELECT DISTINCT ON (legacy_article_id)
    legacy_article_id,
    article_number,
    generic_article_desc,
    brand_name,
    category_name,
    assembly_group_node_id,
    capacity_cc
FROM hk_parts_cache
WHERE
  NOT EXISTS (
    SELECT 1
    FROM unnest(regexp_split_to_array($1, '\s+')) AS query_token(token)
    WHERE concat_ws(' ', generic_article_desc, article_number, category_name) NOT ILIKE '%' || query_token.token || '%'
  )
  AND EXISTS (
    SELECT 1
    FROM unnest(regexp_split_to_array($1, '\s+')) AS query_token(token)
    WHERE concat_ws(' ', generic_article_desc, article_number) ILIKE '%' || query_token.token || '%'
  )
ORDER BY legacy_article_id, generic_article_desc, brand_name
LIMIT $2 OFFSET $3
`

type SearchByTextParams struct {
	RegexpSplitToArray string
	Limit              int32
	Offset             int32
}

type SearchByTextRow struct {
	LegacyArticleID     int32
	ArticleNumber       sql.NullString
	GenericArticleDesc  sql.NullString
	BrandName           sql.NullString
	CategoryName        sql.NullString
	AssemblyGroupNodeID int32
	CapacityCc          sql.NullInt32
}

func (q *Queries) SearchByText(ctx context.Context, arg SearchByTextParams) ([]SearchByTextRow, error) {
	rows, err := q.db.QueryContext(ctx, searchByText, arg.RegexpSplitToArray, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchByTextRow{}
	for rows.Next() {
		var i SearchByTextRow
		if err := rows.Scan(
			&i.LegacyArticleID,
			&i.ArticleNumber,
			&i.GenericArticleDesc,
			&i.BrandName,
			&i.CategoryName,
			&i.AssemblyGroupNodeID,
			&i.CapacityCc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchOEMByNormalized = `-- name: SearchOEMByNormalized :many
SELECT
    raw_number,
    normalized,
    legacy_article_id,
    source_table,
    mfr_name,
    brand_name,
    article_number,
    description
FROM oem_search_index
WHERE normalized = $1
LIMIT $2
`

type SearchOEMByNormalizedParams struct {
	Normalized string
	Limit      int32
}

type SearchOEMByNormalizedRow struct {
	RawNumber       string
	Normalized      string
	LegacyArticleID int32
	SourceTable     string
	MfrName         sql.NullString
	BrandName       sql.NullString
	ArticleNumber   sql.NullString
	Description     sql.NullString
}

func (q *Queries) SearchOEMByNormalized(ctx context.Context, arg SearchOEMByNormalizedParams) ([]SearchOEMByNormalizedRow, error) {
	rows, err := q.db.QueryContext(ctx, searchOEMByNormalized, arg.Normalized, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchOEMByNormalizedRow{}
	for rows.Next() {
		var i SearchOEMByNormalizedRow
		if err := rows.Scan(
			&i.RawNumber,
			&i.Normalized,
			&i.LegacyArticleID,
			&i.SourceTable,
			&i.MfrName,
			&i.BrandName,
			&i.ArticleNumber,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchOEMPrefix = `-- name: SearchOEMPrefix :many
SELECT
    raw_number,
    normalized,
    legacy_article_id,
    source_table,
    mfr_name,
    brand_name,
    article_number,
    description
FROM oem_search_index
WHERE normalized LIKE $1
LIMIT $2
`

type SearchOEMPrefixParams struct {
	Normalized string
	Limit      int32
}

type SearchOEMPrefixRow struct {
	RawNumber       string
	Normalized      string
	LegacyArticleID int32
	SourceTable     string
	MfrName         sql.NullString
	BrandName       sql.NullString
	ArticleNumber   sql.NullString
	Description     sql.NullString
}

func (q *Queries) SearchOEMPrefix(ctx context.Context, arg SearchOEMPrefixParams) ([]SearchOEMPrefixRow, error) {
	rows, err := q.db.QueryContext(ctx, searchOEMPrefix, arg.Normalized, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchOEMPrefixRow{}
	for rows.Next() {
		var i SearchOEMPrefixRow
		if err := rows.Scan(
			&i.RawNumber,
			&i.Normalized,
			&i.LegacyArticleID,
			&i.SourceTable,
			&i.MfrName,
			&i.BrandName,
			&i.ArticleNumber,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
