// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: external_sources.sql

package store

import (
	"context"
)

const createCommonsMediaReview = `-- name: CreateCommonsMediaReview :one
INSERT INTO commons_media_reviews (
    title,
    category_norm,
    media_url,
    thumbnail_url,
    file_page_url,
    license_name,
    license_url,
    attribution,
    source_revision
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, category_norm, media_url, thumbnail_url, file_page_url,
    license_name, license_url, attribution, source_revision, identity_scope,
    review_status, review_notes, reviewed_by, reviewed_at, created_at
`

type CreateCommonsMediaReviewParams struct {
	Title          string
	CategoryNorm   string
	MediaUrl       string
	ThumbnailUrl   string
	FilePageUrl    string
	LicenseName    string
	LicenseUrl     string
	Attribution    string
	SourceRevision string
}

func (q *Queries) CreateCommonsMediaReview(ctx context.Context, arg CreateCommonsMediaReviewParams) (CommonsMediaReview, error) {
	row := q.db.QueryRowContext(ctx, createCommonsMediaReview,
		arg.Title,
		arg.CategoryNorm,
		arg.MediaUrl,
		arg.ThumbnailUrl,
		arg.FilePageUrl,
		arg.LicenseName,
		arg.LicenseUrl,
		arg.Attribution,
		arg.SourceRevision,
	)
	var i CommonsMediaReview
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CategoryNorm,
		&i.MediaUrl,
		&i.ThumbnailUrl,
		&i.FilePageUrl,
		&i.LicenseName,
		&i.LicenseUrl,
		&i.Attribution,
		&i.SourceRevision,
		&i.IdentityScope,
		&i.ReviewStatus,
		&i.ReviewNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findExternalArtifactsBySource = `-- name: FindExternalArtifactsBySource :many
SELECT
    source_key,
    artifact_type,
    title,
    media_url,
    thumbnail_url,
    mime_type,
    exactness,
    confidence,
    license_note,
    provenance_url
FROM external_artifacts
WHERE source_key = $1
ORDER BY
    CASE exactness WHEN 'exact' THEN 0 WHEN 'catalog_group' THEN 1 WHEN 'inferred' THEN 2 ELSE 3 END,
    confidence DESC,
    title
`

type FindExternalArtifactsBySourceRow struct {
	SourceKey     string
	ArtifactType  string
	Title         string
	MediaUrl      string
	ThumbnailUrl  string
	MimeType      string
	Exactness     string
	Confidence    float64
	LicenseNote   string
	ProvenanceUrl string
}

func (q *Queries) FindExternalArtifactsBySource(ctx context.Context, sourceKey string) ([]FindExternalArtifactsBySourceRow, error) {
	rows, err := q.db.QueryContext(ctx, findExternalArtifactsBySource, sourceKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindExternalArtifactsBySourceRow{}
	for rows.Next() {
		var i FindExternalArtifactsBySourceRow
		if err := rows.Scan(
			&i.SourceKey,
			&i.ArtifactType,
			&i.Title,
			&i.MediaUrl,
			&i.ThumbnailUrl,
			&i.MimeType,
			&i.Exactness,
			&i.Confidence,
			&i.LicenseNote,
			&i.ProvenanceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findExternalInstallHintsByPart = `-- name: FindExternalInstallHintsByPart :many
SELECT
    source_key,
    part_number_norm,
    make_norm,
    model_norm,
    hint_type,
    hint_text,
    exactness,
    confidence,
    provenance_url
FROM external_install_hints
WHERE part_number_norm = $1
  AND (make_norm = '' OR make_norm = $2)
  AND (model_norm = '' OR model_norm = $3)
ORDER BY
    CASE exactness WHEN 'exact' THEN 0 WHEN 'catalog_group' THEN 1 WHEN 'inferred' THEN 2 ELSE 3 END,
    confidence DESC,
    source_key
`

type FindExternalInstallHintsByPartParams struct {
	PartNumberNorm string
	MakeNorm       string
	ModelNorm      string
}

type FindExternalInstallHintsByPartRow struct {
	SourceKey      string
	PartNumberNorm string
	MakeNorm       string
	ModelNorm      string
	HintType       string
	HintText       string
	Exactness      string
	Confidence     float64
	ProvenanceUrl  string
}

func (q *Queries) FindExternalInstallHintsByPart(ctx context.Context, arg FindExternalInstallHintsByPartParams) ([]FindExternalInstallHintsByPartRow, error) {
	rows, err := q.db.QueryContext(ctx, findExternalInstallHintsByPart, arg.PartNumberNorm, arg.MakeNorm, arg.ModelNorm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindExternalInstallHintsByPartRow{}
	for rows.Next() {
		var i FindExternalInstallHintsByPartRow
		if err := rows.Scan(
			&i.SourceKey,
			&i.PartNumberNorm,
			&i.MakeNorm,
			&i.ModelNorm,
			&i.HintType,
			&i.HintText,
			&i.Exactness,
			&i.Confidence,
			&i.ProvenanceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommonsMediaReviews = `-- name: ListCommonsMediaReviews :many
SELECT id, title, category_norm, media_url, thumbnail_url, file_page_url,
    license_name, license_url, attribution, source_revision, identity_scope,
    review_status, review_notes, reviewed_by, reviewed_at, created_at
FROM commons_media_reviews
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListCommonsMediaReviews(ctx context.Context) ([]CommonsMediaReview, error) {
	rows, err := q.db.QueryContext(ctx, listCommonsMediaReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommonsMediaReview{}
	for rows.Next() {
		var i CommonsMediaReview
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CategoryNorm,
			&i.MediaUrl,
			&i.ThumbnailUrl,
			&i.FilePageUrl,
			&i.LicenseName,
			&i.LicenseUrl,
			&i.Attribution,
			&i.SourceRevision,
			&i.IdentityScope,
			&i.ReviewStatus,
			&i.ReviewNotes,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFacingEligibleSources = `-- name: ListUserFacingEligibleSources :many
SELECT source_key
FROM external_sources
WHERE user_facing_eligible = TRUE
  AND recommendation = $1
  AND false_positive_risk IN ('very_low', 'low')
  AND license_risk IN ('very_low', 'low')
ORDER BY source_key
`

func (q *Queries) ListUserFacingEligibleSources(ctx context.Context, recommendation string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserFacingEligibleSources, recommendation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var source_key string
		if err := rows.Scan(&source_key); err != nil {
			return nil, err
		}
		items = append(items, source_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewCommonsMedia = `-- name: ReviewCommonsMedia :one
UPDATE commons_media_reviews
SET review_status = $2,
    review_notes = $3,
    reviewed_by = $4,
    reviewed_at = NOW()
WHERE id = $1
RETURNING id, title, category_norm, media_url, thumbnail_url, file_page_url,
    license_name, license_url, attribution, source_revision, identity_scope,
    review_status, review_notes, reviewed_by, reviewed_at, created_at
`

type ReviewCommonsMediaParams struct {
	ID           int64
	ReviewStatus string
	ReviewNotes  string
	ReviewedBy   string
}

func (q *Queries) ReviewCommonsMedia(ctx context.Context, arg ReviewCommonsMediaParams) (CommonsMediaReview, error) {
	row := q.db.QueryRowContext(ctx, reviewCommonsMedia,
		arg.ID,
		arg.ReviewStatus,
		arg.ReviewNotes,
		arg.ReviewedBy,
	)
	var i CommonsMediaReview
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CategoryNorm,
		&i.MediaUrl,
		&i.ThumbnailUrl,
		&i.FilePageUrl,
		&i.LicenseName,
		&i.LicenseUrl,
		&i.Attribution,
		&i.SourceRevision,
		&i.IdentityScope,
		&i.ReviewStatus,
		&i.ReviewNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertExternalSource = `-- name: UpsertExternalSource :exec
INSERT INTO external_sources (
    source_key,
    display_name,
    website_url,
    data_type,
    access_method,
    license_risk,
    hyundai_kia_usefulness,
    multi_make_usefulness,
    false_positive_risk,
    recommendation,
    user_facing_eligible,
    freshness_notes,
    rate_limit_notes,
    notes,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, NOW()
)
ON CONFLICT (source_key) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    website_url = EXCLUDED.website_url,
    data_type = EXCLUDED.data_type,
    access_method = EXCLUDED.access_method,
    license_risk = EXCLUDED.license_risk,
    hyundai_kia_usefulness = EXCLUDED.hyundai_kia_usefulness,
    multi_make_usefulness = EXCLUDED.multi_make_usefulness,
    false_positive_risk = EXCLUDED.false_positive_risk,
    recommendation = EXCLUDED.recommendation,
    user_facing_eligible = EXCLUDED.user_facing_eligible,
    freshness_notes = EXCLUDED.freshness_notes,
    rate_limit_notes = EXCLUDED.rate_limit_notes,
    notes = EXCLUDED.notes,
    updated_at = NOW()
`

type UpsertExternalSourceParams struct {
	SourceKey            string
	DisplayName          string
	WebsiteUrl           string
	DataType             string
	AccessMethod         string
	LicenseRisk          string
	HyundaiKiaUsefulness string
	MultiMakeUsefulness  string
	FalsePositiveRisk    string
	Recommendation       string
	UserFacingEligible   bool
	FreshnessNotes       string
	RateLimitNotes       string
	Notes                string
}

func (q *Queries) UpsertExternalSource(ctx context.Context, arg UpsertExternalSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertExternalSource,
		arg.SourceKey,
		arg.DisplayName,
		arg.WebsiteUrl,
		arg.DataType,
		arg.AccessMethod,
		arg.LicenseRisk,
		arg.HyundaiKiaUsefulness,
		arg.MultiMakeUsefulness,
		arg.FalsePositiveRisk,
		arg.Recommendation,
		arg.UserFacingEligible,
		arg.FreshnessNotes,
		arg.RateLimitNotes,
		arg.Notes,
	)
	return err
}

const upsertExternalSourceAssessment = `-- name: UpsertExternalSourceAssessment :exec
INSERT INTO external_source_assessments (
    source_key,
    sample_scope,
    evidence_score,
    precision_score,
    duplicate_noise_score,
    false_positive_score,
    qa_decision,
    rationale,
    assessed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW()
)
ON CONFLICT (source_key) DO UPDATE SET
    sample_scope = EXCLUDED.sample_scope,
    evidence_score = EXCLUDED.evidence_score,
    precision_score = EXCLUDED.precision_score,
    duplicate_noise_score = EXCLUDED.duplicate_noise_score,
    false_positive_score = EXCLUDED.false_positive_score,
    qa_decision = EXCLUDED.qa_decision,
    rationale = EXCLUDED.rationale,
    assessed_at = NOW()
`

type UpsertExternalSourceAssessmentParams struct {
	SourceKey           string
	SampleScope         string
	EvidenceScore       int32
	PrecisionScore      int32
	DuplicateNoiseScore int32
	FalsePositiveScore  int32
	QaDecision          string
	Rationale           string
}

func (q *Queries) UpsertExternalSourceAssessment(ctx context.Context, arg UpsertExternalSourceAssessmentParams) error {
	_, err := q.db.ExecContext(ctx, upsertExternalSourceAssessment,
		arg.SourceKey,
		arg.SampleScope,
		arg.EvidenceScore,
		arg.PrecisionScore,
		arg.DuplicateNoiseScore,
		arg.FalsePositiveScore,
		arg.QaDecision,
		arg.Rationale,
	)
	return err
}
