// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"time"
)

type CommonsMediaReview struct {
	ID             int64
	Title          string
	CategoryNorm   string
	MediaUrl       string
	ThumbnailUrl   string
	FilePageUrl    string
	LicenseName    string
	LicenseUrl     string
	Attribution    string
	SourceRevision string
	IdentityScope  string
	ReviewStatus   string
	ReviewNotes    string
	ReviewedBy     string
	ReviewedAt     sql.NullTime
	CreatedAt      time.Time
}

type ExternalArtifact struct {
	ID            int64
	SourceKey     string
	ArtifactType  string
	Title         string
	MediaUrl      string
	ThumbnailUrl  string
	MimeType      string
	Exactness     string
	Confidence    float64
	LicenseNote   string
	ProvenanceUrl string
	FetchedAt     time.Time
}

type ExternalInstallHint struct {
	ID             int64
	SourceKey      string
	PartNumberNorm string
	MakeNorm       string
	ModelNorm      string
	HintType       string
	HintText       string
	Exactness      string
	Confidence     float64
	ProvenanceUrl  string
	FetchedAt      time.Time
}

type ExternalPartRef struct {
	ID             int64
	SourceKey      string
	PartNumberNorm string
	BrandNorm      string
	MakeNorm       string
	ModelNorm      string
	VehicleHint    string
	ExactMatch     bool
	Confidence     float64
	ProvenanceUrl  string
	DiscoveredAt   time.Time
}

type ExternalSource struct {
	SourceKey            string
	DisplayName          string
	WebsiteUrl           string
	DataType             string
	AccessMethod         string
	LicenseRisk          string
	HyundaiKiaUsefulness string
	MultiMakeUsefulness  string
	FalsePositiveRisk    string
	Recommendation       string
	UserFacingEligible   bool
	FreshnessNotes       string
	RateLimitNotes       string
	Notes                string
	UpdatedAt            time.Time
}

type ExternalSourceAssessment struct {
	SourceKey           string
	SampleScope         string
	EvidenceScore       int32
	PrecisionScore      int32
	DuplicateNoiseScore int32
	FalsePositiveScore  int32
	QaDecision          string
	Rationale           string
	AssessedAt          time.Time
}

type HkPartsCache struct {
	LinkingTargetID     int32
	LegacyArticleID     int32
	AssemblyGroupNodeID int32
	ArticleNumber       sql.NullString
	GenericArticleDesc  sql.NullString
	DataSupplierID      sql.NullInt32
	BrandName           sql.NullString
	CategoryName        sql.NullString
	VehicleDesc         sql.NullString
	ManuID              sql.NullInt32
	ModelID             sql.NullInt32
	ModelName           sql.NullString
	BeginYearMonth      sql.NullString
	EndYearMonth        sql.NullString
	FuelType            sql.NullString
	CapacityCc          sql.NullInt32
	HorsePowerFrom      sql.NullInt32
}

type HkPlatformMap struct {
	ID           int64
	PlatformCode string
	HyundaiModel string
	KiaModel     string
	GenStartYear sql.NullInt32
	GenEndYear   sql.NullInt32
	Notes        sql.NullString
}

type NhtsaTecdocBridge struct {
	ID              int64
	NhtsaMake       string
	NhtsaModel      string
	YearFrom        int32
	YearTo          int32
	TecdocManuID    int32
	TecdocModelID   int32
	TecdocModelName sql.NullString
}

type OemSearchIndex struct {
	ID              int64
	RawNumber       string
	Normalized      string
	LegacyArticleID int32
	SourceTable     string
	MfrName         sql.NullString
	BrandName       sql.NullString
	ArticleNumber   sql.NullString
	Description     sql.NullString
}

type SubstitutionLink struct {
	FromPartNumber string
	ToPartNumber   string
	Description    sql.NullString
	SourceKey      string
	SourceLabel    string
	SourceDetail   string
	SourceWarning  sql.NullString
	Confidence     float64
}

type VehicleLookup struct {
	NhtsaMake       string
	NhtsaModel      string
	YearFrom        int32
	YearTo          int32
	LinkageTargetID int32
	Description     string
	BeginYearMonth  sql.NullString
	EndYearMonth    sql.NullString
	FuelType        sql.NullString
	CapacityCc      sql.NullInt32
	HorsePowerFrom  sql.NullInt32
}
