// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	BestLinkageTargetCandidates(ctx context.Context, arg BestLinkageTargetCandidatesParams) ([]BestLinkageTargetCandidatesRow, error)
	CategoryTreeLeavesByVehicle(ctx context.Context, linkingTargetID int32) ([]CategoryTreeLeavesByVehicleRow, error)
	CheckPartFitsVehicle(ctx context.Context, arg CheckPartFitsVehicleParams) (bool, error)
	CountPartsByVehicleCategory(ctx context.Context, arg CountPartsByVehicleCategoryParams) (int32, error)
	CountSourcesByRecommendation(ctx context.Context) ([]CountSourcesByRecommendationRow, error)
	CountVehicleSearchParts(ctx context.Context, arg CountVehicleSearchPartsParams) (int32, error)
	CreateCommonsMediaReview(ctx context.Context, arg CreateCommonsMediaReviewParams) (CommonsMediaReview, error)
	FindAlternativesForArticleAnyVehicle(ctx context.Context, arg FindAlternativesForArticleAnyVehicleParams) ([]FindAlternativesForArticleAnyVehicleRow, error)
	FindAlternativesForArticleVehicle(ctx context.Context, arg FindAlternativesForArticleVehicleParams) ([]FindAlternativesForArticleVehicleRow, error)
	FindExternalArtifactsBySource(ctx context.Context, sourceKey string) ([]FindExternalArtifactsBySourceRow, error)
	FindExternalInstallHintsByPart(ctx context.Context, arg FindExternalInstallHintsByPartParams) ([]FindExternalInstallHintsByPartRow, error)
	FindOEMReferencesForArticle(ctx context.Context, legacyArticleID int32) ([]FindOEMReferencesForArticleRow, error)
	FindPartByArticleAnyVehicle(ctx context.Context, legacyArticleID int32) (FindPartByArticleAnyVehicleRow, error)
	FindPartByArticleForVehicle(ctx context.Context, arg FindPartByArticleForVehicleParams) (FindPartByArticleForVehicleRow, error)
	FindPlatformSiblingsForHyundai(ctx context.Context, upper interface{}) ([]FindPlatformSiblingsForHyundaiRow, error)
	FindPlatformSiblingsForKia(ctx context.Context, upper interface{}) ([]FindPlatformSiblingsForKiaRow, error)
	FindVehiclesForArticle(ctx context.Context, arg FindVehiclesForArticleParams) ([]FindVehiclesForArticleRow, error)
	ListAssemblyGroupsByVehicle(ctx context.Context, linkingTargetID int32) ([]ListAssemblyGroupsByVehicleRow, error)
	ListCategoryInfos(ctx context.Context, linkingTargetID int32) ([]ListCategoryInfosRow, error)
	ListCommonsMediaReviews(ctx context.Context) ([]CommonsMediaReview, error)
	ListModelsByMake(ctx context.Context, nhtsaMake string) ([]ListModelsByMakeRow, error)
	ListOEMRawNumbersForArticle(ctx context.Context, legacyArticleID int32) ([]string, error)
	ListPartsByGroup(ctx context.Context, arg ListPartsByGroupParams) ([]ListPartsByGroupRow, error)
	ListPartsByVehicleCategory(ctx context.Context, arg ListPartsByVehicleCategoryParams) ([]ListPartsByVehicleCategoryRow, error)
	ListSubstitutionLinksForArticle(ctx context.Context, legacyArticleID int32) ([]ListSubstitutionLinksForArticleRow, error)
	ListUserFacingEligibleSources(ctx context.Context, recommendation string) ([]string, error)
	ListVehicleSearchCategories(ctx context.Context, linkingTargetID int32) ([]sql.NullString, error)
	ListVehicleSearchParts(ctx context.Context, arg ListVehicleSearchPartsParams) ([]ListVehicleSearchPartsRow, error)
	ListVehicleVariantsByMakeModel(ctx context.Context, arg ListVehicleVariantsByMakeModelParams) ([]ListVehicleVariantsByMakeModelRow, error)
	LookupAlternativeDescription(ctx context.Context, legacyArticleID int32) (sql.NullString, error)
	ResolveLinkageTargets(ctx context.Context, arg ResolveLinkageTargetsParams) ([]ResolveLinkageTargetsRow, error)
	ReverseVehiclesByArticle(ctx context.Context, arg ReverseVehiclesByArticleParams) ([]ReverseVehiclesByArticleRow, error)
	ReviewCommonsMedia(ctx context.Context, arg ReviewCommonsMediaParams) (CommonsMediaReview, error)
	SearchByArticleNumber(ctx context.Context, arg SearchByArticleNumberParams) ([]SearchByArticleNumberRow, error)
	SearchByText(ctx context.Context, arg SearchByTextParams) ([]SearchByTextRow, error)
	SearchOEMByNormalized(ctx context.Context, arg SearchOEMByNormalizedParams) ([]SearchOEMByNormalizedRow, error)
	SearchOEMPrefix(ctx context.Context, arg SearchOEMPrefixParams) ([]SearchOEMPrefixRow, error)
	UpsertExternalSource(ctx context.Context, arg UpsertExternalSourceParams) error
	UpsertExternalSourceAssessment(ctx context.Context, arg UpsertExternalSourceAssessmentParams) error
}

var _ Querier = (*Queries)(nil)
