-- ============================================================================
-- MySQL migration 08 — articlecriteria criteria_value index HOTFIX
-- ============================================================================
-- sql/07_articlecriteria_indexes.sql declares TWO indexes on articlecriteria:
--
--   * idx_articlecriteria_legacyArticleId
--   * idx_articlecriteria_criteria_value    ← this one never applied
--
-- The 2026-08-26 TecDoc-health diagnostic
-- (scripts/diagnostics/tecdoc_health_report.sql section 2) revealed that
-- on the current qa TecDoc MySQL, ONLY THE FIRST INDEX was applied:
--
--   check_name                              | status
--   ----------------------------------------|-------------------------
--   idx_articlecriteria_legacyArticleId     | PRESENT
--   idx_articlecriteria_criteria_value      | MISSING (sql/07 needed)
--
-- Root cause of the partial apply: the second CREATE INDEX statement in
-- sql/07 errored with:
--
--   ERROR 1170 (42000): BLOB/TEXT column 'criteriaDescription' used in
--   key specification without a key length
--
-- because TecDoc dumps articlecriteria.criteriaDescription and
-- articlecriteria.rawValue as TEXT columns, not VARCHAR — and MySQL
-- refuses to index a TEXT/BLOB column without a prefix length.
--
-- This hotfix migration is minimal: it re-applies ONLY the missing index
-- WITH the correct prefix lengths so MySQL will accept it, without
-- re-running the DDL that already succeeded.
--
-- ─ Prefix-length choice ────────────────────────────────────────────────
--
-- The diagnostic v1 section 6 output revealed the actual data shape:
-- criteriaDescription values are short human-readable spec names
-- ("Fitting Position", "Length [mm]", "Brake Disc Thickness [mm]",
-- "Supplementary Article/Supplementary Info") — nothing longer than
-- ~50 chars.
--
-- rawValue is spec-value text ("M20 x 1.5", "front-left", "18.5",
-- "5 (S3)") — also typically <30 chars.
--
-- Chosen prefix: 191 chars per column. Rationale:
--   * 191 chars × 4 bytes/utf8mb4 = 764 bytes per column
--   * 764 × 2 = 1528 bytes total compound index
--   * Well within MySQL 8 InnoDB's 3072-byte index-prefix limit
--   * 191 is the ROW-based convention (Rails/Laravel/Doctrine) for
--     "max utf8mb4 index prefix that always fits"
--   * Massively over-provisioned for actual TecDoc data (5-50 char
--     values), so equality lookup is fully selective — the index acts
--     like a full-column index in practice
--
-- ─ Impact of the missing index (from the 2026-08-22 audit) ─────────────
--
--   FindBySpecMatch (strategy_spec_match.go:225-258)
--     runs `WHERE criteriaDescription = ? AND rawValue = ?` against 27M
--     rows without an index — hits the ctx deadline on every enrichment
--     call. This is one of the reasons AvgOEMxRef sits at 0 in the
--     2026-08-25 post-deploy audit.
--
-- ─ Migration properties ────────────────────────────────────────────────
--
--   * Data-preserving — pure DDL, adds one index, no column mutations
--   * MySQL 8.0+ ONLINE — non-blocking on the Aiven managed instance
--   * Idempotent-to-failure — if the index IS already there, MySQL
--     rejects with ERROR 1061 (Duplicate key name); safe to ignore
--   * Reversible
--
-- ROLLBACK:
--
--   ALTER TABLE articlecriteria DROP INDEX idx_articlecriteria_criteria_value;
--
-- Estimated DDL time: 5-15 min on 27M rows.
-- Runs online — no application downtime.
-- ============================================================================

-- Compound index — criteriaDescription first because it has bounded
-- cardinality (~few hundred distinct spec names); rawValue has high
-- cardinality. Full selectivity for the AND-of-equalities pattern in
-- strategy_spec_match.go FindBySpecMatch.
--
-- (191) is the utf8mb4-safe index-prefix length; TecDoc actual values
-- are all shorter, so the index behaves as if fully covering.
CREATE INDEX idx_articlecriteria_criteria_value
  ON articlecriteria (criteriaDescription(191), rawValue(191));

-- ─ Verification queries (advisory, no side effects) ────────────────────
-- Run AFTER the DDL completes to confirm the index is healthy and used.
--
-- -- Confirm the index exists:
-- SHOW INDEX FROM articlecriteria
--   WHERE Key_name = 'idx_articlecriteria_criteria_value';
--
-- -- Confirm the query planner uses it
-- -- (expect: key='idx_articlecriteria_criteria_value', type='ref'):
-- EXPLAIN
--   SELECT DISTINCT a.legacyArticleId, a.articleNumber
--   FROM articlecriteria ac
--   JOIN articles a ON a.legacyArticleId = ac.legacyArticleId
--   WHERE ac.criteriaDescription = 'Thread Size'
--     AND ac.rawValue = 'M20 x 1.5'
--   LIMIT 10;
